apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
